site_name: Carmine Impact Docs
site_url: https://harpnetstudios.github.io/cardboard/
site_author: YellowberryHN
repo_url: https://github.com/HarpNetStudios/cardboard

docs_dir: raw
site_dir: ../docs

theme:
  name: material
  logo: assets/logo.svg
  navigation_depth: 3
  palette:
    primary: custom
    accent: custom
    scheme: slate
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.sections
    - navigation.tracking
    - toc.follow
extra_css:
  - css/extra.css
  
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - offline
markdown_extensions:
    - callouts
    - toc:
        permalink: #
        toc_depth: 6
    - attr_list
nav:
  - Home: index.md
  - Info:
    - Command Reference: game.md
    - Configuration: config.md
    - Editing Tutorial: editing.md
    - Editing Reference: editref.md
    - Model Reference: models.md